# Generated by Django 4.1.5 on 2023-06-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthYMD',
            field=models.CharField(default='000101', max_length=6),
            preserve_default=False,
        ),
    ]
